# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gps.proto',
  package='gps',
  syntax='proto2',
  serialized_pb=_b('\n\tgps.proto\x12\x03gps*a\n\nSampleType\x12\n\n\x06\x41\x43TION\x10\x00\x12\x14\n\x10\x41NGULAR_POSITION\x10\x01\x12\x14\n\x10\x41NGULAR_VELOCITY\x10\x02\x12\x10\n\x0cTARGET_POINT\x10\x03\x12\t\n\x05NOISE\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SAMPLETYPE = _descriptor.EnumDescriptor(
  name='SampleType',
  full_name='gps.SampleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANGULAR_POSITION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANGULAR_VELOCITY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TARGET_POINT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOISE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=18,
  serialized_end=115,
)
_sym_db.RegisterEnumDescriptor(_SAMPLETYPE)

SampleType = enum_type_wrapper.EnumTypeWrapper(_SAMPLETYPE)
ACTION = 0
ANGULAR_POSITION = 1
ANGULAR_VELOCITY = 2
TARGET_POINT = 3
NOISE = 4


DESCRIPTOR.enum_types_by_name['SampleType'] = _SAMPLETYPE


# @@protoc_insertion_point(module_scope)
